### ISSUE TITLE
Do not build on Fedora 39 with kernel 3.8.4

### ISSUE THREAD

**Issue by o1e9** [aircrack-ng/rtl8814au#106]
Hi,

After upgrading the kernel to 6.8.4 on my Fedora 39 installation, the make stops over IPX header obstacle:

```
${HOME}/rtl8814au/core/rtw_br_ext.c:20:18: fatal error: net/ipx.h: No such file or directory
   20 |         #include <net/ipx.h>
      |                  ^~~~~~~~~~~
```
It seems net/ipx.h had been deprecated at some point, so has to be removed from the driver, I guess.

Thanks,
Oleg
