### ISSUE TITLE
Compilation error for arch linux latest kernel `Error! Bad return status for module build on kernel: 6.7.1-arch1-1 (x86_64)`

### ISSUE THREAD

**Issue by nikelborm** [aircrack-ng/rtl8814au#105]
I don't know what other info may be useful to you, so please ask questions
Also here are build logs of the error happened for `rtl8814au`
```plaintext
DKMS make.log for rtl8814au-5.8.5.1.r171.gf058ea8 for kernel 6.7.1-arch1-1 (x86_64)
Wed Jan 24 19:51:00 MSK 2024
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.7.1-arch1-1/build M=/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build  modules
make[1]: Entering directory '/usr/lib/modules/6.7.1-arch1-1/build'
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_io.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_ioctl_query.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_ieee80211.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_mlme.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_mlme_ext.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_mi.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_wlan_util.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_vht.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_pwrctrl.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_rf.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_chplan.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_recv.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_sta_mgt.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_ap.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/mesh/rtw_mesh.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/mesh/rtw_mesh_pathtbl.o
In file included from ./include/linux/kernel.h:31,
                 from ./arch/x86/include/asm/percpu.h:27,
                 from ./arch/x86/include/asm/nospec-branch.h:14,
                 from ./arch/x86/include/asm/paravirt_types.h:20,
                 from ./arch/x86/include/asm/ptrace.h:97,
                 from ./arch/x86/include/asm/math_emu.h:5,
                 from ./arch/x86/include/asm/processor.h:13,
                 from ./arch/x86/include/asm/timex.h:5,
                 from ./include/linux/timex.h:67,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:13,
                 from /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/include/basic_types.h:76,
                 from /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/include/drv_types.h:26,
                 from /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_rf.c:17:
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_rf.c: In function ‘dump_txpwr_lmt’:
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_rf.c:1082:67: warning: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
 1082 |                                                                 , strcmp(ent->regd_name, rfctl->regd_name) == 0 ? rf_path_char(path) : ' ');
      |                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/printk.h:427:33: note: in definition of macro ‘printk_index_wrap’
  427 |                 _p_func(_fmt, ##__VA_ARGS__);                           \
      |                                 ^~~~~~~~~~~
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/include/rtw_debug.h:85:26: note: in expansion of macro ‘printk’
   85 |         #define _dbgdump printk
      |                          ^~~~~~
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/include/rtw_debug.h:233:25: note: in expansion of macro ‘_RTW_PRINT’
  233 |                         _RTW_PRINT(fmt, ##arg); \
      |                         ^~~~~~~~~~
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_rf.c:1081:57: note: in expansion of macro ‘_RTW_PRINT_SEL’
 1081 |                                                         _RTW_PRINT_SEL(sel, "%3c "
      |                                                         ^~~~~~~~~~~~~~
In file included from /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_rf.c:18:
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/include/hal_data.h:341:14: note: source object ‘regd_name’ of size 0
  341 |         char regd_name[0];
      |              ^~~~~~~~~
In file included from /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/include/drv_types.h:60:
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_rf.c:1082:67: warning: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
 1082 |                                                                 , strcmp(ent->regd_name, rfctl->regd_name) == 0 ? rf_path_char(path) : ' ');
      |                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/include/rtw_debug.h:235:46: note: in definition of macro ‘_RTW_PRINT_SEL’
  235 |                         _seqdump(sel, fmt, ##arg) /*rtw_warn_on(1)*/; \
      |                                              ^~~
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/include/hal_data.h:341:14: note: source object ‘regd_name’ of size 0
  341 |         char regd_name[0];
      |              ^~~~~~~~~
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_xmit.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_p2p.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_rson.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_tdls.o
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_rf.c: In function ‘_rtw_txpwr_lmt_get_by_name’:
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_rf.c:1328:21: warning: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
 1328 |                 if (strcmp(ent->regd_name, regd_name) == 0) {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/include/hal_data.h:341:14: note: source object ‘regd_name’ of size 0
  341 |         char regd_name[0];
      |              ^~~~~~~~~
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_br_ext.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_iol.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_sreset.o
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_mlme_ext.c: In function ‘rtw_txpwr_init_regd’:
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_mlme_ext.c:197:21: warning: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
  197 |                 if (strcmp(exc->regd_name, regd_str(TXPWR_LMT_NONE)) == 0)
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/include/drv_types.h:62,
                 from /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_mlme_ext.c:17:
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/include/rtw_rf.h:197:14: note: source object ‘regd_name’ of size 0
  197 |         char regd_name[0];
      |              ^~~~~~~~~
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_mlme_ext.c:199:26: warning: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
  199 |                 else if (strcmp(exc->regd_name, regd_str(TXPWR_LMT_WW)) == 0)
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/include/rtw_rf.h:197:14: note: source object ‘regd_name’ of size 0
  197 |         char regd_name[0];
      |              ^~~~~~~~~
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_btcoex_wifionly.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_btcoex.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_beamforming.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_odm.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_rm.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_rm_fsm.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/rtw_rm_util.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/core/efuse/rtw_efuse.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/osdep_service.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/os_intfs.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/usb_intf.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/usb_ops_linux.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/ioctl_linux.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/xmit_linux.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/mlme_linux.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/recv_linux.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/ioctl_cfg80211.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/rtw_cfgvendor.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/wifi_regd.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/rtw_android.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/rtw_proc.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/rtw_rhashtable.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/hal_intf.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/hal_com.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/hal_com_phycfg.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/hal_phy.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/hal_dm.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/hal_dm_acs.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/hal_btcoex_wifionly.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/hal_btcoex.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/hal_mp.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/hal_mcc.o
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/ioctl_cfg80211.c:9934:26: error: initialization of ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_ap_update *)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_beacon_data *)’ [-Werror=incompatible-pointer-types]
 9934 |         .change_beacon = cfg80211_rtw_change_beacon,
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/ioctl_cfg80211.c:9934:26: note: (near initialization for ‘rtw_cfg80211_ops.change_beacon’)
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/hal_hci/hal_usb.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/led/hal_led.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/led/hal_usb_led.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/HalPwrSeqCmd.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/rtl8814a/Hal8814PwrSeq.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/rtl8814a/rtl8814a_xmit.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/rtl8814a/rtl8814a_sreset.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/rtl8814a/rtl8814a_hal_init.o
  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/rtl8814a/rtl8814a_phycfg.o
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/ioctl_cfg80211.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/led/hal_led.c: In function ‘rtw_led_set_strategy’:
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/hal/led/hal_led.c:66:38: warning: implicit conversion from ‘enum _LED_STATE’ to ‘LED_CTL_MODE’ {aka ‘enum _LED_CTL_MODE’} [-Wenum-conversion]
   66 |         rtw_led_control(pri_adapter, RTW_LED_OFF);
      |                                      ^~~~~~~~~~~
make[2]: *** [/usr/lib/modules/6.7.1-arch1-1/build/Makefile:1911: /var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.7.1-arch1-1/build'
make: *** [Makefile:2398: modules] Error 2
```

**Comment by nikelborm** [comment]
This issue may be related: https://github.com/tomaspinho/rtl8821ce/issues/344
On the same kernel it has the same error
```plaintext
/var/lib/dkms/rtl8814au/5.8.5.1.r171.gf058ea8/build/os_dep/linux/ioctl_cfg80211.c:9934:26: error: initialization of ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_ap_update *)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_beacon_data *)’ [-Werror=incompatible-pointer-types]
 9934 |         .change_beacon = cfg80211_rtw_change_beacon,
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
```
