### PR TITLE
Fix for compilation error for linux kernel >=5.12 because of GRO_DROP deprecation

### PR DESCRIPTION
**Pull request by ayushbindlish**
Fixed gro_drop compilation error on kernels >=5.12

### CODE REVIEW

**Comment by ayushbindlish** [comment]
@kimocoder @aircrack-ng Can we get an update on this pull request?

**Comment by s0kil** [comment]
I've tried this patch yesterday, and it worked for me, on pop-os.

**Comment by SwampRabbit** [comment]
I can verify that this allows building on Debian 11 with kernel 5.14.6-3

**Comment by sovrasov** [comment]
That fix works on my machine with Ubuntu 21.10 / kernel 5.13.0-20

**Comment by DomiRusz24** [comment]
(This has been since resolved, the solution isn't related to this driver.)

First time compiling, it worked flawlessly, after restart, the driver stopped working. Tried removing it, recompiling it and installing it again, doesn't work.

8814au/5.8.5.1, 5.14.16-arch1-1, x86_64: installed (WARNING! Diff between built and installed module!)

May be something related:
/sys/module/8814au/parameters/rtw_switch_usb_mode: No such file or directory.

**Comment by zhouxv** [comment]
It works for me!! 3q
My PC: Ubunut 20.04 LTS / kenel 5.13.0-25-generic
